baseURL = 'https://myblog-eight-dusky.vercel.app/'
languageCode = 'zh-cn'
title = '技术文档站'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSearch = true
  BookSection = 'docs'
  BookMenuBundle = '/menu'
  BookRepo = ''
  BookEditPath = ''
  BookPortableLinks = true

[outputs]
  home = ['HTML', 'RSS']
  section = ['HTML', 'RSS']

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
